train: C:/Users/daunk/Capstone-Project/milestone3/data/images/train
val:   C:/Users/daunk/Capstone-Project/milestone3/data/images/val
test:  C:/Users/daunk/Capstone-Project/milestone3/data/images/test

nc: 3
names: ["caries(anterior)", "caries(posterior)", "healthy"]